# Generated by Django 5.0.5 on 2024-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_survey_organisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
