# Generated by Django 5.0.3 on 2024-05-07 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_survey_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='all',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_answered',
            field=models.ManyToManyField(blank=True, related_name='already_answered', to=settings.AUTH_USER_MODEL),
        ),
    ]
