# Generated by Django 5.0.3 on 2024-05-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='next_schedule',
            field=models.DateTimeField(blank=True, default="2004-10-31"),
            preserve_default=False,
        ),
    ]
