# Generated by Django 5.0.3 on 2024-05-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_survey_next_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='next_schedule',
        ),
    ]
