# Generated by Django 5.0.3 on 2024-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_remove_survey_next_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
